# Generated by Django 4.1.1 on 2022-09-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatar_default.jpg', upload_to='images'),
        ),
    ]
