# Generated by Django 4.1.1 on 2022-09-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='date')),
                ('checkin', models.TimeField(auto_now=True, verbose_name='check in')),
                ('checkout', models.TimeField(auto_now=True, verbose_name='check in')),
                ('time', models.IntegerField()),
            ],
        ),
    ]
