# Generated by Django 4.1.1 on 2022-09-13 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='checkin',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='check in'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='checkout',
            field=models.TimeField(blank=True, null=True, verbose_name='check in'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
