# Generated by Django 4.1.1 on 2022-09-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_timesheet_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='checkin',
            field=models.TimeField(blank=True, null=True, verbose_name='check in'),
        ),
    ]
