# Generated by Django 4.1.1 on 2022-09-13 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_timesheet_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='checkin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='check in'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='check out'),
        ),
    ]
