# Generated by Django 4.1.1 on 2022-09-13 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_timesheet_checkin_alter_timesheet_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
