# Generated by Django 4.1.1 on 2022-09-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_timesheet_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
