# Generated by Django 4.1.1 on 2022-09-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_timesheet_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
