# Generated by Django 4.1.1 on 2022-09-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_timesheet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
