# Generated by Django 4.1.1 on 2022-09-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_timesheet_day_timesheet_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='date',
        ),
    ]
