# Generated by Django 4.1.1 on 2022-09-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_timesheet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
