# Generated by Django 4.1.1 on 2022-09-14 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_timesheet_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 10, 55, 29, 231391), verbose_name='check in'),
        ),
    ]
