# Generated by Django 4.1.1 on 2022-09-14 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_timesheet_late_alter_timesheet_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='ot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='checkin',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 13, 12, 37, 37157), verbose_name='check in'),
        ),
    ]
