# Generated by Django 4.1.1 on 2022-09-14 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_timesheet_ot_alter_timesheet_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='checkin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='check in'),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(blank=True, null=True)),
                ('w_time', models.IntegerField(blank=True, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
