# Generated by Django 4.1.1 on 2022-09-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_timesheet_checkin_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='profile',
            name='certificate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='certificate'),
        ),
        migrations.AddField(
            model_name='profile',
            name='citizen_identification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='citizen identification'),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='degree'),
        ),
        migrations.AddField(
            model_name='profile',
            name='license_plates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='license_plates'),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='marital_status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tax_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='tax code'),
        ),
    ]
